import json
import os

AUTHENTIC_MALDIVES_POIS = [
  {
    "poi_id": "MLD_01",
    "name": "Maafushi Island Coral Reef Snorkeling & Sea Turtles",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Marine & Coral",
    "rating": 4.9,
    "entry_fee_inr": 2500,
    "avg_spend_inr": 3500,
    "ideal_duration_hrs": 3.5,
    "lat": 3.9405,
    "lon": 73.4907,
    "tags": "maafushi island, sea turtles, coral reefs, reef sharks, clownfish, maldives",
    "description": "Snorkel over pristine coral atolls with wild hawksbill sea turtles, friendly nurse sharks, and schools of vibrant reef fish."
  },
  {
    "poi_id": "MLD_02",
    "name": "Private Sandbank Picnic & Turquoise Lagoon Dip",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Luxury & Relaxation",
    "rating": 5.0,
    "entry_fee_inr": 4500,
    "avg_spend_inr": 6000,
    "ideal_duration_hrs": 3.5,
    "lat": 4.1755,
    "lon": 73.5093,
    "tags": "sandbank, isolated sandbar, turquoise lagoon, gourmet lunch, maldives",
    "description": "Speedboat transfer to an uninhabited gleaming white sandbank surrounded by 360 degrees of crystal-clear turquoise waters."
  },
  {
    "poi_id": "MLD_03",
    "name": "Hanifaru Bay UNESCO Manta Ray & Whale Shark Sanctuary",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "UNESCO Marine Reserve",
    "rating": 5.0,
    "entry_fee_inr": 6000,
    "avg_spend_inr": 7500,
    "ideal_duration_hrs": 4.0,
    "lat": 5.1711,
    "lon": 73.1481,
    "tags": "baa atoll, unesco biosphere, manta ray cyclone, whale sharks, marine sanctuary, maldives",
    "description": "World-famous UNESCO marine reserve in Baa Atoll where dozens of majestic manta rays and whale sharks aggregate to filter-feed on plankton."
  },
  {
    "poi_id": "MLD_04",
    "name": "Male Grand Friday Mosque (Hukuru Miskiy) & Islamic Centre",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Heritage & Architecture",
    "rating": 4.7,
    "entry_fee_inr": 0,
    "avg_spend_inr": 200,
    "ideal_duration_hrs": 1.5,
    "lat": 4.1775,
    "lon": 73.5126,
    "tags": "male city, coral stone mosque, golden dome, islamic center, history, maldives",
    "description": "17th-century coral stone mosque intricately carved with Arabic calligraphy and royal tombs, crowned by a magnificent golden dome."
  },
  {
    "poi_id": "MLD_05",
    "name": "Banana Reef World-Class Coral Scuba Diving",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Scuba Diving & Coral",
    "rating": 4.9,
    "entry_fee_inr": 5500,
    "avg_spend_inr": 7000,
    "ideal_duration_hrs": 3.0,
    "lat": 4.2386,
    "lon": 73.5417,
    "tags": "banana reef, north male atoll, overhangs, moray eels, bannerfish, scuba dive, maldives",
    "description": "The Maldives' first discovered dive site featuring dramatic underwater cliffs, coral overhangs, giant moray eels, and swirling schools of bannerfish."
  },
  {
    "poi_id": "MLD_06",
    "name": "Overwater Bungalow Sunset Dolphin Cruise",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Sunset Cruise",
    "rating": 4.8,
    "entry_fee_inr": 3200,
    "avg_spend_inr": 4000,
    "ideal_duration_hrs": 2.5,
    "lat": 4.2000,
    "lon": 73.5200,
    "tags": "sunset dhoni, spinner dolphins, overwater villa view, champagne cruise, maldives",
    "description": "Traditional wooden Dhoni boat cruise at golden hour to spot pods of playful spinner dolphins leaping against the Indian Ocean sunset."
  },
  {
    "poi_id": "MLD_07",
    "name": "Vaadhoo Island 'Sea of Stars' Bioluminescent Beach Walk",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Natural Wonder",
    "rating": 4.9,
    "entry_fee_inr": 0,
    "avg_spend_inr": 500,
    "ideal_duration_hrs": 2.0,
    "lat": 5.8622,
    "lon": 72.9936,
    "tags": "sea of stars, bioluminescent phytoplankton, glowing waves, vaadhoo rhaa atoll, maldives",
    "description": "Rare natural phenomenon where millions of microscopic ostracod crustaceans and phytoplankton illuminate the night surf with electric blue starlight."
  },
  {
    "poi_id": "MLD_08",
    "name": "Fulidhoo Island Friendly Stingray & Nurse Shark Lagoon",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Wildlife Encounter",
    "rating": 4.8,
    "entry_fee_inr": 1800,
    "avg_spend_inr": 2500,
    "ideal_duration_hrs": 2.5,
    "lat": 3.6811,
    "lon": 73.4158,
    "tags": "fulidhoo, vaavu atoll, stingrays on beach, nurse sharks, shallow waters, maldives",
    "description": "Idyllic local island in Vaavu Atoll where wild yet gentle stingrays and tawny nurse sharks swim right up to the shoreline in knee-deep water."
  },
  {
    "poi_id": "MLD_09",
    "name": "South Ari Atoll Giant Whale Shark Snorkeling Safari",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Marine Adventure",
    "rating": 5.0,
    "entry_fee_inr": 5000,
    "avg_spend_inr": 6500,
    "ideal_duration_hrs": 4.5,
    "lat": 3.5358,
    "lon": 72.8428,
    "tags": "south ari atoll, whale sharks, gentle giants, snorkeling expedition, ocean safari, maldives",
    "description": "Guided open-ocean expedition to swim alongside the gentle 30-foot whale sharks that patrol the outer reefs of South Ari Atoll year-round."
  },
  {
    "poi_id": "MLD_10",
    "name": "Male Local Fish Market & Artisan Produce Bazaar",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Culture & Markets",
    "rating": 4.6,
    "entry_fee_inr": 0,
    "avg_spend_inr": 400,
    "ideal_duration_hrs": 1.5,
    "lat": 4.1789,
    "lon": 73.5089,
    "tags": "yellowfin tuna, male fish market, fresh coconuts, betel leaves, local lifestyle, maldives",
    "description": "Bustling harbor market where local fishermen unload massive yellowfin tuna and skipjack, alongside stalls of sweet mangoes and king coconuts."
  },
  {
    "poi_id": "MLD_11",
    "name": "National Museum of Maldives (Sultan Park)",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "History & Artifacts",
    "rating": 4.6,
    "entry_fee_inr": 300,
    "avg_spend_inr": 400,
    "ideal_duration_hrs": 2.0,
    "lat": 4.1764,
    "lon": 73.5111,
    "tags": "sultan park, royal thrones, lacquerware, ancient coins, sultanate history, maldives",
    "description": "Housed inside Sultan Park, displaying royal ceremonial thrones, ornamental palanquins, lacquerware crafts, and 12th-century Buddhist stone carvings."
  },
  {
    "poi_id": "MLD_12",
    "name": "Hulhumale Beachfront Promenade & Water Sports Hub",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Beach & Watersports",
    "rating": 4.7,
    "entry_fee_inr": 1200,
    "avg_spend_inr": 2000,
    "ideal_duration_hrs": 3.0,
    "lat": 4.2136,
    "lon": 73.5389,
    "tags": "hulhumale, parasailing, jet ski, seaside promenade, modern island, maldives",
    "description": "Paved beachfront promenade with palm-lined cycling trails, beachside smoothie cafes, parasailing, and stand-up paddleboarding."
  },
  {
    "poi_id": "MLD_13",
    "name": "Whale Submarine Deep-Sea Coral Trenches Tour",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Submarine Adventure",
    "rating": 4.8,
    "entry_fee_inr": 6500,
    "avg_spend_inr": 7500,
    "ideal_duration_hrs": 2.0,
    "lat": 4.1800,
    "lon": 73.5050,
    "tags": "whale submarine, 100ft underwater, coral trenches, yellow boxfish, shipwreck, maldives",
    "description": "Descend 100 feet beneath the Indian Ocean surface in a climate-controlled passenger submarine to observe deep coral reefs and shipwrecks."
  },
  {
    "poi_id": "MLD_14",
    "name": "Biyadhoo Island House Reef & Manta Point Snorkel",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Snorkeling & Reef",
    "rating": 4.8,
    "entry_fee_inr": 2200,
    "avg_spend_inr": 3000,
    "ideal_duration_hrs": 3.0,
    "lat": 3.9214,
    "lon": 73.4542,
    "tags": "biyadhoo, natural vegetation, house reef dropoff, eagle rays, coral garden, maldives",
    "description": "One of the best natural house reefs in South Male Atoll, with steep reef drop-offs populated by spotted eagle rays and coral gardens."
  },
  {
    "poi_id": "MLD_15",
    "name": "Rasdhoo Island Hammerhead Shark Diving Spot",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Deep Sea Diving",
    "rating": 4.9,
    "entry_fee_inr": 7000,
    "avg_spend_inr": 8500,
    "ideal_duration_hrs": 3.5,
    "lat": 4.2625,
    "lon": 72.9917,
    "tags": "rasdhoo atoll, hammerhead point, sunrise dive, deep dropoff, pelagic fish, maldives",
    "description": "World-famous early-morning pelagic dive spot where divers descend into the deep blue channel to witness schools of scalloped hammerhead sharks."
  },
  {
    "poi_id": "MLD_16",
    "name": "Dhigurah Island Whale Shark Trail & 3km Sandy Spit",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Beach & Wildlife",
    "rating": 4.9,
    "entry_fee_inr": 1500,
    "avg_spend_inr": 2500,
    "ideal_duration_hrs": 4.0,
    "lat": 3.5300,
    "lon": 72.9300,
    "tags": "dhigurah, long sand spit, whale shark sanctuary, lush jungle, local maldives",
    "description": "One of the longest islands in Maldives featuring a 3km white sand spit tapering into turquoise waters and direct access to whale shark reefs."
  },
  {
    "poi_id": "MLD_17",
    "name": "Ukulhas Island Eco Beach & Waste-Free Village Walk",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Eco Tourism & Beach",
    "rating": 4.8,
    "entry_fee_inr": 0,
    "avg_spend_inr": 500,
    "ideal_duration_hrs": 2.5,
    "lat": 4.2144,
    "lon": 72.8639,
    "tags": "ukulhas, alif alif atoll, green island, bikini beach, eco friendly, maldives",
    "description": "Award-winning eco-friendly local island renowned for spotless white sand beaches, crystalline waters, and traditional Maldivian island hospitality."
  },
  {
    "poi_id": "MLD_18",
    "name": "Thulusdhoo Island Cokes Surf Break & Surfboard Workshop",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Surfing & Crafts",
    "rating": 4.7,
    "entry_fee_inr": 2000,
    "avg_spend_inr": 3000,
    "ideal_duration_hrs": 3.0,
    "lat": 4.3736,
    "lon": 73.6500,
    "tags": "thulusdhoo, cokes surf break, chickens reef, custom surfboard shaper, drums boduberu, maldives",
    "description": "The capital of Maldivian surf culture, famous for the world-class 'Cokes' right-hander wave break and traditional Boduberu drumming sessions."
  },
  {
    "poi_id": "MLD_19",
    "name": "Sinamale Bridge & Boduthakurufaanu Magu Sunset Walk",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Cityscape & Promenade",
    "rating": 4.6,
    "entry_fee_inr": 0,
    "avg_spend_inr": 200,
    "ideal_duration_hrs": 1.5,
    "lat": 4.1750,
    "lon": 73.5250,
    "tags": "sinamale bridge, ocean overpass, male hulhumale connection, sea breeze, sunset point, maldives",
    "description": "Scenic 2.1km ocean overpass connecting Male, Hulhule airport, and Hulhumale with sweeping views over the turquoise ocean."
  },
  {
    "poi_id": "MLD_20",
    "name": "Kuramathi Island Sandbank Sunset & Marine Biology Center",
    "city": "Maldives",
    "region": "Asia",
    "country": "Maldives",
    "category": "Eco Centre & Sandbank",
    "rating": 4.9,
    "entry_fee_inr": 1200,
    "avg_spend_inr": 2000,
    "ideal_duration_hrs": 2.5,
    "lat": 4.2600,
    "lon": 72.9800,
    "tags": "kuramathi, 1km sandbank, coral propagation, sperm whale skeleton, marine biology, maldives",
    "description": "Dramatic 1km sandbank stretching into the horizon, featuring an interactive Marine Biology Center with a complete sperm whale skeleton and coral nurseries."
  }
]

def update_dataset():
    data_file = "datasets/destinations/destinations_rich_knowledge.json"
    with open(data_file, "r", encoding="utf-8") as f:
        existing = json.load(f)

    # Remove any old Maldives entries
    filtered = [d for d in existing if d.get("city") != "Maldives"]
    updated = AUTHENTIC_MALDIVES_POIS + filtered

    with open(data_file, "w", encoding="utf-8") as f:
        json.dump(updated, f, indent=2)

    print(f"Updated {data_file} with {len(updated)} total POIs, including {len(AUTHENTIC_MALDIVES_POIS)} authentic Maldives attractions!")

if __name__ == "__main__":
    update_dataset()
