import json
import os

EXTRA_DESTINATIONS = {
    "Switzerland": [
        {"poi_id": "SWI_01", "name": "Jungfraujoch - Top of Europe & Aletsch Glacier (3,454m)", "category": "Alpine Peak", "rating": 5.0, "entry_fee_inr": 6500, "ideal_duration_hrs": 5.0, "lat": 46.5475, "lon": 7.9825, "tags": "jungfraujoch, top of europe, aletsch glacier, ice palace, switzerland", "description": "Highest railway station in Europe with Ice Palace sculptures and views over the Aletsch Glacier."},
        {"poi_id": "SWI_02", "name": "Mount Pilatus World's Steepest Cogwheel Railway", "category": "Mountain Adventure", "rating": 4.9, "entry_fee_inr": 3500, "ideal_duration_hrs": 4.0, "lat": 46.9792, "lon": 8.2536, "tags": "mount pilatus, 48 degree cogwheel, dragon trail, lucerne, switzerland", "description": "Iconic dragon mountain ascended via the world's steepest 48-degree cogwheel railway from Alpnachstad."},
        {"poi_id": "SWI_03", "name": "Chapel Bridge (Kapellbrücke) & Water Tower in Lucerne", "category": "Historic Bridge", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 1.5, "lat": 47.0516, "lon": 8.3075, "tags": "chapel bridge, kapellbrucke, wooden bridge 1333, reuss river, switzerland", "description": "14th-century covered wooden footbridge spanning the Reuss River adorned with historic triangular paintings."},
        {"poi_id": "SWI_04", "name": "Interlaken Harder Kulm Panoramic Two Lakes Bridge", "category": "Funicular Viewpoint", "rating": 4.8, "entry_fee_inr": 1800, "ideal_duration_hrs": 2.5, "lat": 46.6975, "lon": 7.8631, "tags": "harder kulm, interlaken, lake thun, lake brienz, eiger view, switzerland", "description": "Glass-bottomed viewing bridge over Lake Brienz and Lake Thun with the Eiger, Mönch, and Jungfrau peaks."},
        {"poi_id": "SWI_05", "name": "Grindelwald First Cliff Walk by Tissot", "category": "Cliff Walk", "rating": 4.9, "entry_fee_inr": 3200, "ideal_duration_hrs": 3.5, "lat": 46.6583, "lon": 8.0567, "tags": "grindelwald first, cliff walk, first flyer, bachpalpsee, switzerland", "description": "Suspension footbridge hugging sheer alpine cliffs leading to the First Flyer zip line and Lake Bachalpsee."},
        {"poi_id": "SWI_06", "name": "Lauterbrunnen Valley of 72 Waterfalls & Staubbach Falls", "category": "Waterfalls & Valley", "rating": 4.9, "entry_fee_inr": 0, "ideal_duration_hrs": 3.0, "lat": 46.5936, "lon": 7.9078, "tags": "lauterbrunnen, staubbach falls, 72 waterfalls, tolkiens rivendell, switzerland", "description": "Enchanting glacial trough valley lined with 72 roaring waterfalls, inspiring Tolkien's Rivendell."},
        {"poi_id": "SWI_07", "name": "Zermatt & Matterhorn Glacier Paradise (3,883m)", "category": "Glacier Paradise", "rating": 5.0, "entry_fee_inr": 7500, "ideal_duration_hrs": 5.0, "lat": 45.9764, "lon": 7.7489, "tags": "matterhorn, zermatt, highest cable car, 3883m, switzerland", "description": "Europe's highest mountain station offering year-round skiing and direct views of the iconic Matterhorn."},
        {"poi_id": "SWI_08", "name": "Lake Brienz Turquoise Steamboat Cruise & Giessbach Falls", "category": "Lake Cruise", "rating": 4.8, "entry_fee_inr": 2400, "ideal_duration_hrs": 3.0, "lat": 46.7333, "lon": 7.9667, "tags": "lake brienz, steamboat, giessbach falls, grandhotel, switzerland", "description": "Glide across glacial turquoise waters on a historic paddle steamer to the 14-stage Giessbach waterfalls."},
        {"poi_id": "SWI_09", "name": "Rhine Falls Neuhausen (Europe's Largest Waterfall)", "category": "Natural Wonder", "rating": 4.8, "entry_fee_inr": 500, "ideal_duration_hrs": 2.5, "lat": 47.6778, "lon": 8.6156, "tags": "rhine falls, schaffhausen, largest waterfall, rock boat trip, switzerland", "description": "Thunderous 150-meter-wide cataract where 600,000 liters of water plunge over the limestone shelf per second."},
        {"poi_id": "SWI_10", "name": "Bern Old City UNESCO Clock Tower (Zytglogge)", "category": "UNESCO Capital", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 46.9480, "lon": 7.4474, "tags": "bern, zytglogge, astronomical clock, 6km arcades, aare river, switzerland", "description": "Medieval capital featuring 13th-century astronomical clock tower and 6km of sandstone shopping arcades."},
        {"poi_id": "SWI_11", "name": "Mount Titlis Rotair Revolving Cable Car & Glacier Cave", "category": "Glacier Cable Car", "rating": 4.9, "entry_fee_inr": 5800, "ideal_duration_hrs": 4.0, "lat": 46.7722, "lon": 8.4375, "tags": "titlis, engelberg, rotair 360, cliff walk, glacier cave, switzerland", "description": "The world's first revolving cable car ascending to 3,020 meters, featuring an underground blue glacier cave."},
        {"poi_id": "SWI_12", "name": "Lake Geneva & Chillon Castle in Montreux", "category": "Lakeside Castle", "rating": 4.8, "entry_fee_inr": 1500, "ideal_duration_hrs": 2.5, "lat": 46.4142, "lon": 6.9275, "tags": "chillon castle, lake geneva, montreux, lord byron, switzerland", "description": "Island castle fortress on Lake Geneva immortalized by Lord Byron, surrounded by alpine peaks."},
        {"poi_id": "SWI_13", "name": "Zurich Altstadt Old Town, Grossmünster & Lindenhof", "category": "Historic City", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 47.3717, "lon": 8.5422, "tags": "zurich, grossmunster, lindenhof, limmat river, altstadt, switzerland", "description": "Cobblestone alleys of Old Town Zurich with twin-towered Romanesque cathedral and riverside squares."},
        {"poi_id": "SWI_14", "name": "Trümmelbach Falls Subterranean Glacial Caves", "category": "Glacial Gorge", "rating": 4.8, "entry_fee_inr": 1200, "ideal_duration_hrs": 2.0, "lat": 46.5700, "lon": 7.9133, "tags": "trummelbach falls, 10 glacial waterfalls, inside mountain, lauterbrunnen, switzerland", "description": "Europe's only subterranean glacial waterfalls, draining 20,000 liters of water inside the mountain."},
        {"poi_id": "SWI_15", "name": "Gornergrat Cogwheel Train & 29 Four-Thousand-Meter Peaks", "category": "Scenic Railway", "rating": 5.0, "entry_fee_inr": 6800, "ideal_duration_hrs": 4.0, "lat": 45.9833, "lon": 7.7833, "tags": "gornergrat, 3089m, riffelsee reflection, matterhorn, switzerland", "description": "Open-air cogwheel railway ascending to 3,089m with reflections of the Matterhorn in Lake Riffelsee."},
        {"poi_id": "SWI_16", "name": "St. Moritz Alpine Lake & Glacier Express Panoramic Train", "category": "Scenic Train", "rating": 4.9, "entry_fee_inr": 4500, "ideal_duration_hrs": 4.0, "lat": 46.4908, "lon": 9.8355, "tags": "st moritz, engadin, glacier express, landwasser viaduct, switzerland", "description": "World-famous luxury alpine resort and scenic glass-roofed train across the Landwasser Viaduct."},
        {"poi_id": "SWI_17", "name": "Aare Gorge (Aareschlucht) Limestone Chasm Walk", "category": "Limestone Gorge", "rating": 4.7, "entry_fee_inr": 800, "ideal_duration_hrs": 2.0, "lat": 46.7183, "lon": 8.2056, "tags": "aare gorge, aareschlucht, meiringen, wooden walkway, switzerland", "description": "1.4km wooden walkway through a 200-meter-deep narrow limestone gorge carved by the Aare River."},
        {"poi_id": "SWI_18", "name": "Lindt Home of Chocolate Interactive Museum & 9m Fountain", "category": "Chocolate Museum", "rating": 4.8, "entry_fee_inr": 1600, "ideal_duration_hrs": 2.0, "lat": 47.3167, "lon": 8.5333, "tags": "lindt chocolate, chocolate fountain 9m, tasting room, kilchberg, switzerland", "description": "State-of-the-art interactive chocolate museum featuring a 9-meter real chocolate fountain and tastings."},
        {"poi_id": "SWI_19", "name": "Lake Thun Castle Trail & Spiez Bay Promenade", "category": "Lakeside Castles", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 46.6833, "lon": 7.6833, "tags": "lake thun, oberhofen castle, spiez bay, vineyards, switzerland", "description": "Fairytale lakeside castles including Oberhofen and Spiez surrounded by hillside vineyards."},
        {"poi_id": "SWI_20", "name": "Schilthorn Piz Gloria 360° Revolving James Bond Summit", "category": "Revolving Summit", "rating": 4.9, "entry_fee_inr": 5500, "ideal_duration_hrs": 4.0, "lat": 46.5572, "lon": 7.8350, "tags": "schilthorn, piz gloria, james bond 007, revolving restaurant, murren, switzerland", "description": "Iconic revolving summit restaurant at 2,970 meters, filming location for James Bond 007."}
    ],

    "Dubai": [
        {"poi_id": "DXB_01", "name": "Burj Khalifa 'At The Top' 124th & 148th Observation Decks", "category": "Observation Tower", "rating": 4.9, "entry_fee_inr": 3800, "ideal_duration_hrs": 2.5, "lat": 25.1972, "lon": 55.2744, "tags": "burj khalifa, 828m, highest observation deck, skyline, dubai", "description": "The world's tallest building (828m) offering 360-degree views over the Arabian Gulf and desert."},
        {"poi_id": "DXB_02", "name": "The Dubai Mall & Illuminated Fountain Symphony", "category": "Mall & Fountains", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 3.0, "lat": 25.1985, "lon": 55.2796, "tags": "dubai mall, dancing fountain, aquarium underwater zoo, dubai", "description": "The world's largest shopping mall with giant indoor aquarium and synchronized dancing fountains."},
        {"poi_id": "DXB_03", "name": "Dubai Desert Safari, 4x4 Dune Bashing & BBQ Bedouin Camp", "category": "Desert Safari", "rating": 4.9, "entry_fee_inr": 2800, "ideal_duration_hrs": 5.5, "lat": 24.9500, "lon": 55.4500, "tags": "desert safari, red dunes, dune bashing, belly dance, tanoura, bbq camp, dubai", "description": "Thrilling 4x4 dune bashing across red dunes, camel rides, sandboarding, and Bedouin dinner camp."},
        {"poi_id": "DXB_04", "name": "Museum of the Future Interactive Sci-Fi Experience", "category": "Futuristic Museum", "rating": 4.9, "entry_fee_inr": 3400, "ideal_duration_hrs": 3.0, "lat": 25.2253, "lon": 55.2819, "tags": "museum of future, torus ring, arabic calligraphy, 2071 space, dubai", "description": "Architectural masterpiece shaped like a silver torus adorned with Arabic poetry, exploring future tech."},
        {"poi_id": "DXB_05", "name": "Palm Jumeirah & Atlantis Aquaventure Waterpark", "category": "Waterpark & Luxury", "rating": 4.9, "entry_fee_inr": 6500, "ideal_duration_hrs": 5.0, "lat": 25.1304, "lon": 55.1171, "tags": "palm jumeirah, aquaventure, leap of faith slide, the lost chambers, dubai", "description": "The world's largest waterpark featuring 105 record-breaking slides and shark tank tunnels."},
        {"poi_id": "DXB_06", "name": "Dubai Marina Dhow Dinner Cruise & Marina Promenade", "category": "Dinner Cruise", "rating": 4.7, "entry_fee_inr": 2200, "ideal_duration_hrs": 2.5, "lat": 25.0772, "lon": 55.1333, "tags": "dubai marina, illuminated dhow cruise, skyscrapers, jbr walk, dubai", "description": "Evening cruise on a traditional wooden boat gliding between illuminated supertall skyscrapers."},
        {"poi_id": "DXB_07", "name": "Dubai Miracle Garden 150-Million Flower Sculptures", "category": "Botanical Wonder", "rating": 4.8, "entry_fee_inr": 1600, "ideal_duration_hrs": 2.5, "lat": 25.0597, "lon": 55.2444, "tags": "miracle garden, emirates a380 floral, floral castle, heart tunnel, dubai", "description": "The world's largest natural flower garden displaying 150 million blooming flowers in 2D and 3D designs."},
        {"poi_id": "DXB_08", "name": "Old Dubai Al Fahidi Historic Quarter, Gold & Spice Souk Abra", "category": "Heritage & Souks", "rating": 4.7, "entry_fee_inr": 100, "ideal_duration_hrs": 3.0, "lat": 25.2631, "lon": 55.2972, "tags": "al fahidi, gold souk, spice souk, abra boat 1 aed, wind towers, dubai", "description": "Traditional wind-tower architecture and crossing Dubai Creek on a wooden Abra to the Gold & Spice Souks."},
        {"poi_id": "DXB_09", "name": "Dubai Frame 150m Glass Skybridge Viewpoint", "category": "Modern Landmark", "rating": 4.7, "entry_fee_inr": 1200, "ideal_duration_hrs": 1.5, "lat": 25.2344, "lon": 55.3003, "tags": "dubai frame, glass floor skybridge, old dubai new dubai view, zaabeel park, dubai", "description": "150-meter-tall golden picture frame with a glass bridge connecting views of historic Old Dubai with New Dubai."},
        {"poi_id": "DXB_10", "name": "Global Village 90+ Cultures Pavilions & Street Food", "category": "Culture & Carnival", "rating": 4.8, "entry_fee_inr": 500, "ideal_duration_hrs": 4.0, "lat": 25.0683, "lon": 55.3022, "tags": "global village, 90 cultures, floating market, carnival stunts, street food, dubai", "description": "Massive multicultural festival park featuring pavilions from over 90 countries with street foods and shows."},
        {"poi_id": "DXB_11", "name": "Madinat Jumeirah Arabian Venetian Canals & Burj Al Arab View", "category": "Arabian Venice", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 25.1331, "lon": 55.1853, "tags": "madinat jumeirah, souk madinat, abra canals, burj al arab view, dubai", "description": "Luxurious Arabian resort styled like an ancient citadel with 5km of waterways and close views of Burj Al Arab."},
        {"poi_id": "DXB_12", "name": "JBR The Beach & Ain Dubai Giant Ferris Wheel", "category": "Beachfront Promenade", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 25.0789, "lon": 55.1319, "tags": "jbr beach, ain dubai, bluewaters island, camel rides on beach, dubai", "description": "Lively beachfront destination with restaurants, watersports, and pedestrian bridge to Bluewaters Island."},
        {"poi_id": "DXB_13", "name": "Ski Dubai Indoor Snow Park & Penguin Encounter", "category": "Indoor Snow", "rating": 4.8, "entry_fee_inr": 4800, "ideal_duration_hrs": 3.0, "lat": 25.1181, "lon": 55.1994, "tags": "ski dubai, mall of emirates, subzero snow, king penguins, chairlift, dubai", "description": "22,500 square meter indoor ski resort featuring real snow slopes and Gentoo penguin encounters."},
        {"poi_id": "DXB_14", "name": "The View at The Palm 360° Glass Observatory (52nd Floor)", "category": "Palm Observatory", "rating": 4.8, "entry_fee_inr": 2200, "ideal_duration_hrs": 2.0, "lat": 25.1150, "lon": 55.1417, "tags": "the view at the palm, palm tower 52nd floor, nakheel mall, dubai", "description": "Observation deck 240 meters high offering the clearest 360-degree panorama of the Palm Jumeirah archipelago."},
        {"poi_id": "DXB_15", "name": "Dubai Glow Garden & Dinosaur Park", "category": "Light Sculptures", "rating": 4.6, "entry_fee_inr": 1500, "ideal_duration_hrs": 2.5, "lat": 25.2280, "lon": 55.2950, "tags": "glow garden, 10 million led lights, animatronic dinosaurs, zaabeel park, dubai", "description": "Enchanting illuminated theme park crafted from 10 million energy-saving bulbs and 120 animatronic dinosaurs."},
        {"poi_id": "DXB_16", "name": "Al Qudra Desert Love Lakes & Wildlife Flamingo Sanctuary", "category": "Desert Oasis", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 24.8400, "lon": 55.3600, "tags": "love lake, heart shaped lake, al qudra, flamingos, oryx, desert sunset, dubai", "description": "Man-made heart-shaped oasis lakes in the desert home to over 170 native bird species and black swans."},
        {"poi_id": "DXB_17", "name": "Dubai Safari Park Asian & African Wildlife Safari", "category": "Wildlife Safari", "rating": 4.7, "entry_fee_inr": 1100, "ideal_duration_hrs": 3.5, "lat": 25.1780, "lon": 55.4420, "tags": "dubai safari park, african lions, white rhinos, moon bears, open safari, dubai", "description": "119-hectare eco-friendly wildlife reserve sheltering 3,000 animals in climate-controlled natural habitats."},
        {"poi_id": "DXB_18", "name": "La Mer Beachfront Street Art & Seaside Dining", "category": "Beachfront Art", "rating": 4.6, "entry_fee_inr": 0, "ideal_duration_hrs": 2.0, "lat": 25.2289, "lon": 55.2650, "tags": "la mer, jumeirah beach, funky graffiti murals, watersports, beach cafes, dubai", "description": "Trendy urban beachfront destination known for colorful industrial graffiti murals and seafood cafes."},
        {"poi_id": "DXB_19", "name": "Deep Dive Dubai World's Deepest Pool (60m Sunken City)", "category": "Deep Diving", "rating": 4.9, "entry_fee_inr": 8500, "ideal_duration_hrs": 2.5, "lat": 25.1311, "lon": 55.2989, "tags": "deep dive dubai, 60m depth, sunken city, scuba arcade, world record, dubai", "description": "Record-breaking 60-meter-deep diving pool themed as an abandoned underwater sunken city."},
        {"poi_id": "DXB_20", "name": "Sky Views Dubai Glass Slide & Edge Walk (219m)", "category": "Sky Adventure", "rating": 4.8, "entry_fee_inr": 1900, "ideal_duration_hrs": 1.5, "lat": 25.1990, "lon": 55.2680, "tags": "sky views, address sky view, glass slide, edge walk 219m, burj views, dubai", "description": "Transparent glass slide wrapped around the 53rd floor exterior of Address Sky View hotel overlooking Burj Khalifa."}
    ],

    "Jaipur": [
        {"poi_id": "JAI_01", "name": "Amber Fort (Amer Palace) & Sheesh Mahal Mirror Palace", "category": "Hilltop Fort", "rating": 4.9, "entry_fee_inr": 500, "ideal_duration_hrs": 3.5, "lat": 26.9855, "lon": 75.8513, "tags": "amber fort, sheesh mahal, diwan-e-aam, maota lake, elephant path, jaipur", "description": "16th-century Rajput citadel built from yellow and pink sandstone, famed for its thousand-mirror Sheesh Mahal."},
        {"poi_id": "JAI_02", "name": "Hawa Mahal (Palace of Winds) 953 Jharokha Facade", "category": "Iconic Monument", "rating": 4.8, "entry_fee_inr": 200, "ideal_duration_hrs": 1.5, "lat": 26.9239, "lon": 75.8267, "tags": "hawa mahal, palace of winds, 953 windows, pink city, jaipur", "description": "Five-story honeycomb palace with 953 intricately carved jharokha casements allowing royal ladies to observe bazaars."},
        {"poi_id": "JAI_03", "name": "City Palace & Peacock Gate Royal Courtyard", "category": "Royal Palace", "rating": 4.8, "entry_fee_inr": 300, "ideal_duration_hrs": 2.5, "lat": 26.9258, "lon": 75.8236, "tags": "city palace, chandra mahal, peacock gate, royal family, armory, jaipur", "description": "Grand blend of Rajput and Mughal architecture housing royal textile museums, armories, and the current Maharaja's residence."},
        {"poi_id": "JAI_04", "name": "Nahargarh Fort Aravali Sunset Viewpoint & Stepwell", "category": "Sunset Fort", "rating": 4.8, "entry_fee_inr": 200, "ideal_duration_hrs": 2.5, "lat": 26.9378, "lon": 75.8156, "tags": "nahargarh, sunset point, padao cafe, aravali hills, bawdi stepwell, jaipur", "description": "Hilltop fortress towering over the entire Pink City, famed for stunning golden hour sunsets over the Aravali range."},
        {"poi_id": "JAI_05", "name": "Jantar Mantar UNESCO World Heritage Astronomical Observatory", "category": "UNESCO Science", "rating": 4.8, "entry_fee_inr": 200, "ideal_duration_hrs": 2.0, "lat": 26.9248, "lon": 75.8246, "tags": "jantar mantar, unesco, samrat yantra sundial, astronomy, sawai jai singh, jaipur", "description": "Collection of 19 stone astronomical instruments built in 1734, including the world's largest stone sundial."},
        {"poi_id": "JAI_06", "name": "Jal Mahal Floating Water Palace on Man Sagar Lake", "category": "Water Palace", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 1.5, "lat": 26.9535, "lon": 75.8462, "tags": "jal mahal, water palace, man sagar lake, submerged palace, photography, jaipur", "description": "Stunning red sandstone palace appearing to float in the center of Man Sagar Lake against the Aravali hills."},
        {"poi_id": "JAI_07", "name": "Jaigarh Fort & Jaivana (World's Largest Wheeled Cannon)", "category": "Military Fortress", "rating": 4.7, "entry_fee_inr": 150, "ideal_duration_hrs": 2.0, "lat": 26.9850, "lon": 75.8456, "tags": "jaigarh fort, jaivana cannon 50 tonnes, underground tunnels, cheel ka teela, jaipur", "description": "Rugged hilltop military fortress preserving the 50-tonne Jaivana cannon and secret underground tunnels connecting to Amer."},
        {"poi_id": "JAI_08", "name": "Albert Hall Central State Museum & Pigeon Square", "category": "State Museum", "rating": 4.7, "entry_fee_inr": 150, "ideal_duration_hrs": 2.0, "lat": 26.9116, "lon": 75.8194, "tags": "albert hall, indo-saracenic, egyptian mummy, miniature paintings, night illumination, jaipur", "description": "Rajasthan's oldest museum housed in an ornate Indo-Saracenic palace displaying an Egyptian mummy and blue pottery."},
        {"poi_id": "JAI_09", "name": "Johari Bazaar & Bapu Bazaar Artisan Shopping", "category": "Bazaars & Crafts", "rating": 4.6, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 26.9200, "lon": 75.8250, "tags": "gemstones jewelry, jaipuri quilts razai, bandhani textiles, camel leather juttis, jaipur", "description": "Vibrant pink-arcaded markets famous for precious gemstones, handcrafted Jaipuri quilts, and bandhani silks."},
        {"poi_id": "JAI_10", "name": "Chokhi Dhani Ethnic Rajasthani Village & Thali Feast", "category": "Cultural Resort", "rating": 4.8, "entry_fee_inr": 1200, "ideal_duration_hrs": 4.0, "lat": 26.7667, "lon": 75.8333, "tags": "chokhi dhani, ghoomar dance, camel rides, dal baati churma, puppet show, jaipur", "description": "5-star ethnic village resort offering Kalbeliya folk dances, puppet shows, camel rides, and royal Dal Baati Churma feasts."},
        {"poi_id": "JAI_11", "name": "Galta Ji (Monkey Temple) Natural Mountain Spring", "category": "Sacred Springs", "rating": 4.6, "entry_fee_inr": 0, "ideal_duration_hrs": 2.0, "lat": 26.9167, "lon": 75.8667, "tags": "galta ji, monkey temple, 7 sacred kunds, natural springs, rhesus macaques, jaipur", "description": "Ancient Hindu pilgrimage complex situated in a mountain pass, famous for seven natural freshwater kunds."},
        {"poi_id": "JAI_12", "name": "Patrika Gate & Jawahar Circle Musical Fountain", "category": "Architecture & Garden", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 1.5, "lat": 26.8489, "lon": 75.8014, "tags": "patrika gate, hand painted pillars, jawahar circle, musical fountain, jaipur", "description": "Stunning nine-column gateway hand-painted with murals of Rajasthan's royal history and vibrant cultural heritage."},
        {"poi_id": "JAI_13", "name": "Panna Meena Ka Kund Ancient Geometric Stepwell", "category": "Geometric Stepwell", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 1.0, "lat": 26.9856, "lon": 75.8569, "tags": "panna meena ka kund, stepwell, symmetrical stairs, amer village, photography, jaipur", "description": "16th-century eight-story stepwell with mesmerizing symmetrical criss-cross staircases near Amer Fort."},
        {"poi_id": "JAI_14", "name": "Sisodia Rani Garden & Royal Terraced Cascades", "category": "Royal Garden", "rating": 4.5, "entry_fee_inr": 100, "ideal_duration_hrs": 1.5, "lat": 26.8833, "lon": 75.8667, "tags": "sisodia rani garden, multi tier garden, radha krishna murals, natural spring fountains, jaipur", "description": "Multi-terraced royal pleasure garden painted with Radha-Krishna murals and natural spring fountains."},
        {"poi_id": "JAI_15", "name": "Royal Gaitor Cenotaphs (Chhatris of Maharajas)", "category": "Marble Cenotaphs", "rating": 4.7, "entry_fee_inr": 100, "ideal_duration_hrs": 1.5, "lat": 26.9400, "lon": 75.8300, "tags": "royal gaitor, white marble chhatris, carved dome cenotaphs, peaceful valley, jaipur", "description": "Peaceful valley sanctuary with intricately carved white marble domed cenotaphs commemorating the Kachhwaha kings."},
        {"poi_id": "JAI_16", "name": "Anokhi Museum of Hand Printing & Block Workshop", "category": "Craft Museum", "rating": 4.7, "entry_fee_inr": 150, "ideal_duration_hrs": 2.0, "lat": 26.9880, "lon": 75.8550, "tags": "anokhi museum, woodblock printing, indigo dye, textile heritage, haveli, jaipur", "description": "Restored 16th-century haveli dedicated to preserving the traditional art of Rajasthani woodblock textile printing."},
        {"poi_id": "JAI_17", "name": "Birla Mandir (Laxmi Narayan Temple) White Marble Shrine", "category": "Marble Temple", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 1.5, "lat": 26.8928, "lon": 75.8153, "tags": "birla mandir, pure white makrana marble, moti dungri hill, night lighting, jaipur", "description": "Pure white Makrana marble temple built on Moti Dungri hill, illuminated magically against the night sky."},
        {"poi_id": "JAI_18", "name": "Govind Dev Ji Temple Royal Aarti Ceremony", "category": "Spiritual Aarti", "rating": 4.9, "entry_fee_inr": 0, "ideal_duration_hrs": 1.5, "lat": 26.9280, "lon": 75.8240, "tags": "govind dev ji, lord krishna, royal aarti, city palace complex, spiritual devotion, jaipur", "description": "Historic shrine of Lord Krishna within the City Palace complex where thousands gather for melodious daily aartis."},
        {"poi_id": "JAI_19", "name": "Jawahar Kala Kendra Arts Center & Shilpgram Crafts", "category": "Art & Crafts Center", "rating": 4.6, "entry_fee_inr": 0, "ideal_duration_hrs": 2.0, "lat": 26.8790, "lon": 75.8050, "tags": "jawahar kala kendra, charles correa design, nine planets navagraha, art exhibitions, jaipur", "description": "Multi-arts centre designed by Charles Correa based on the Navagraha astronomical grid with craft workshops."},
        {"poi_id": "JAI_20", "name": "Chandlai Lake Migratory Flamingo Wetland", "category": "Wetland & Birding", "rating": 4.6, "entry_fee_inr": 0, "ideal_duration_hrs": 2.0, "lat": 26.6800, "lon": 75.8800, "tags": "chandlai lake, flamingos, migratory birds, tranquil wetland, photography, jaipur", "description": "Scenic 140-year-old freshwater lake 30km from Jaipur attracting thousands of pink flamingos and pelicans."}
    ]
}

def merge_all():
    file_path = "datasets/destinations/destinations_rich_knowledge.json"
    existing = []
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            existing = json.load(f)

    # Filter out replaced destinations
    replaced_keys = set(EXTRA_DESTINATIONS.keys())
    kept = [d for d in existing if d.get("city") not in replaced_keys]

    added = []
    for city, pois in EXTRA_DESTINATIONS.items():
        for p in pois:
            p["city"] = city
            p["region"] = p.get("region", "Global")
            p["country"] = p.get("country", city)
            added.append(p)

    final_list = added + kept
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(final_list, f, indent=2)

    print(f"Added extra cities! Total POIs in knowledge base: {len(final_list)}")

if __name__ == "__main__":
    merge_all()
